Vichar/Vichar/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls import url
from . import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.HomePage.as_view(),name='home'),
    url(r"^vicha_app/", include("vicha_app.urls", namespace="vicha_app")),
    url(r"^vicha_app/", include("django.contrib.auth.urls")),
    url(r"^test/$", views.TestPage.as_view(), name="test"),
    url(r"^thanks/$", views.ThanksPage.as_view(), name="thanks"),
    url(r"^posts/", include("posts.urls", namespace="posts")),
    url(r"^groups/",include("groups.urls", namespace="groups")),
]

Vichar/posts/urls.py
from django.conf.urls import url

from . import views

app_name='posts'

urlpatterns = [
    url(r"^$", views.PostList.as_view(), name="all"),
    url(r"new/$", views.CreatePost.as_view(), name="create"),
    url(r"by/(?P<username>[-\w]+)/$",views.UserPosts.as_view(),name="for_user"),
    url(r"by/(?P<username>[-\w]+)/(?P<pk>\d+)/$",views.PostDetail.as_view(),name="single"),
    url(r"delete/(?P<pk>\d+)/$",views.DeletePost.as_view(),name="delete"),
]

Vichar/vicha_app/urls.py
# from django.contrib import admin
# from django.urls import path
# from django.urls.resolvers import URLPattern
# from . import views
# from django.views.generic import (View,TemplateView,ListView,DetailView,
#                                   CreateView,DeleteView,UpdateView)
# urlpatterns=[
#      path('',views.HomePage.as_view(),name='home'),
#  ]
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from . import views

app_name = 'vicha_app'

urlpatterns = [
    url(r"login/$", auth_views.LoginView.as_view(template_name="vicha_app/login.html"),name='login'),
    url(r"logout/$", auth_views.LogoutView.as_view(), name="logout"),
    url(r"signup/$", views.SignUp.as_view(), name="signup"),
]

Vichar/templates/base.html
{%load static%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Base page</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">

    <!-- Optional theme -->
    <!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous"> -->

    <!-- Latest compiled and minified JavaScript -->
    <!-- <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script> -->


    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'Vichar/css/master.css'%}">
    <!-- <link rel="stylesheet" href="{% static 'css/master.css'%}"> -->
</head>
<body>


    <nav class="navbar navbar-expand-lg  bg-light mynav" role="navigation" id="navbar">
        <div class="container my-3 mynav">

    <a class="navbar-brand mynav" href="{% url 'home' %}">Vichar</a>

                <ul class="nav navbar-nav navbar-right">
                    {% if user.is_authenticated %}
                    <li><a href="{% url 'posts:create' %}" class="btn btn-simple">Posts</a></li>
                    <li><a href="{% url 'groups:all' %}" class="btn btn-simple">Groups</a></li>
                    <li><a href="{% url 'groups:create' %}" class="btn btn-simple">Create Group</a></li>
                    <li><a href="{% url 'vicha_app:logout' %}" class="btn btn-simple">Log out</a></li>
                          {% else %}
                          <li><a href="{% url 'groups:all' %}"class="btn btn-simple">Groups</a></li>
                          <li><a href="{% url 'vicha_app:login' %}" class="btn btn-default">Log in</a></li>
                          <li><a href="{% url 'vicha_app:signup' %}" class="btn btn-simple">Sign up</a></li>
                    {% endif %}
                </ul>



        </div>
    </nav>
    <div class="container mycontent">
        {% block content %}

        {% endblock %}

      </div>
    
</body>
<canvas id="canvas"></canvas>
<script type="text/Javascript" src="{% static 'Vichar/js/master.js'%}"></script>
<canvas id="canvas"></canvas>
<!-- <script type="text/Javascript" src="{% static 'Vichar/js/master.js'%}"></script> -->
</html>

Vichar/templates/index.html
{%extends 'base.html'%}
{%block content%}
<h2>Welcome to vichar app</h2>
{%endblock%}

Vichar/templates/test.html
{% extends "base.html" %}
{% block content %}
<div class="container">
  <h1>You are now logged in!</h1>
  <h2><a href="{% url 'groups:all'%}">Go to Groups</a></h2>


</div>




{% endblock %}

Vichar/templates/thanks.html
{% extends "base.html" %}
{% block content %}
<h1>Thanks for visiting! Come back soon!</h1>

{% endblock %}